#!/usr/bin/env bash
# Prepares apps/web for design-sync. Run from the repo root before package-build.mjs.
# apps/web is a private SPA with no library build, so we synthesize what the
# converter needs: a barrel entry, a types entry + .d.ts tree, and compiled CSS.
set -euo pipefail
cd "$(dirname "$0")/.."

# 1. Barrel entry over the real ui/ source (+ ThemeProvider, which Toaster needs).
{
  echo "// Generated by .design-sync/prepare.sh — do not edit."
  for f in apps/web/src/components/ui/*.tsx; do
    echo "export * from './src/components/ui/$(basename "$f" .tsx)'"
  done
  echo "export * from './src/components/theme-provider'"
} > apps/web/ds-entry.ts

# 2. Declarations. Non-dotted paths only: the converter's .d.ts glob skips dot
#    entries, and its types entry falls back to <pkg>/index.d.ts.
rm -rf apps/web/ds-types
(cd apps/web && npx tsc -p .ds-tsconfig.json)
echo "export * from './ds-types/ds-entry'" > apps/web/index.d.ts

# 3. Compiled CSS. src/index.css is Tailwind *source*, so it must be compiled.
#    We do NOT reuse vite's app bundle output: Tailwind tree-shakes to the classes
#    the app happens to use, which silently drops utilities the preview cards and
#    the design agent need. .ds-tailwind.css re-exports the same tokens but also
#    scans .design-sync/previews and carries a semantic-token safelist.
#    @font-face is stripped: it points at vite's /assets/*.woff2, which we do not
#    ship; cfg.extraFonts supplies working faces from @fontsource-variable.
node .ds-sync/node_modules/@tailwindcss/cli/dist/index.mjs \
  -i apps/web/.ds-tailwind.css -o apps/web/.ds-compiled.css --minify
node -e '
const fs=require("fs");
const p="apps/web/.ds-compiled.css";
const css=fs.readFileSync(p,"utf8").replace(/@font-face\s*\{[^}]*\}/g,"");
fs.writeFileSync(p,css);
console.log("css:",p,css.length,"bytes");
'
