import type { IngredientOriginType, TriStateFlag } from '../types.ts'
import { normalizeInci } from '../types.ts'

/**
 * Formulation knowledge, separate from the shelf.
 *
 * Inventory answers "what do I own". This library answers "what exists, what it does,
 * and how much of it belongs in a finished product". The agent fills a skeleton from
 * here; the inventory only flags what needs ordering.
 *
 * Percents are % w/w of the finished product. Perfume aroma materials are given at
 * finished-product level for an eau de parfum (concentrate 15–25%).
 */

export type MaterialRole =
  | 'water'
  | 'humectant'
  | 'emulsifier'
  | 'co_emulsifier'
  | 'emollient'
  | 'butter'
  | 'wax'
  | 'thickener'
  | 'chelator'
  | 'ph_adjuster'
  | 'preservative'
  | 'preservative_booster'
  | 'antioxidant'
  | 'active'
  | 'solubilizer'
  | 'solvent'
  | 'carrier'
  | 'aroma_material'
  | 'fixative'
  | 'fragrance_compound'
  | 'colorant'

export const MATERIAL_ROLE_LABELS: Record<MaterialRole, string> = {
  water: 'Water',
  humectant: 'Humectant',
  emulsifier: 'Emulsifier',
  co_emulsifier: 'Co-emulsifier / consistency',
  emollient: 'Emollient (oil or ester)',
  butter: 'Butter',
  wax: 'Wax',
  thickener: 'Thickener / gelling agent',
  chelator: 'Chelator',
  ph_adjuster: 'pH adjuster',
  preservative: 'Preservative',
  preservative_booster: 'Preservative booster',
  antioxidant: 'Antioxidant',
  active: 'Active',
  solubilizer: 'Solubiliser',
  solvent: 'Solvent',
  carrier: 'Carrier oil',
  aroma_material: 'Aroma material',
  fixative: 'Fixative',
  fragrance_compound: 'Fragrance compound',
  colorant: 'Colourant',
}

export type MaterialPhase = 'water' | 'oil' | 'cool_down' | 'concentrate' | 'solvent'

export type Material = {
  inci: string
  /** Trade or common names people type instead of the INCI. */
  aliases?: string[]
  cas?: string
  roles: MaterialRole[]
  phase: MaterialPhase
  /** Usual use band, % w/w of the finished product. */
  typical: [number, number]
  /** Hard ceiling (regulatory or technical). Above this the draft is rejected. */
  max?: number
  solubility: 'water' | 'oil' | 'both' | 'alcohol'
  /** Add below 40 °C. */
  coolDown?: boolean
  animalDerived: TriStateFlag
  originType: IngredientOriginType
  /** EU fragrance allergen — must appear on the label above the threshold. */
  allergen?: boolean
  /** Short process or compatibility note the agent can pass on. */
  notes?: string
}

const m = (material: Material) => material

export const MATERIALS: Material[] = [
  // ---------------------------------------------------------------- water phase
  m({
    inci: 'Aqua',
    aliases: ['Water', 'Aqua (Water)', 'Water (Aqua)', 'Eau'],
    roles: ['water', 'solvent'],
    phase: 'water',
    typical: [30, 90],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Deionised or distilled. Balance of the water phase: whatever is left after the other rows.',
  }),
  m({
    inci: 'Glycerin',
    aliases: ['Glycerine', 'Vegetable glycerin'],
    cas: '56-81-5',
    roles: ['humectant'],
    phase: 'water',
    typical: [2, 8],
    max: 20,
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sticky above ~8%. Use it to pre-disperse gums.',
  }),
  m({
    inci: 'Propanediol',
    aliases: ['Zemea'],
    roles: ['humectant', 'solvent', 'preservative_booster'],
    phase: 'water',
    typical: [2, 8],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Corn-derived. Lighter feel than glycerin; helps preservatives.',
  }),
  m({
    inci: 'Butylene Glycol',
    roles: ['humectant', 'solvent'],
    phase: 'water',
    typical: [2, 8],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
  }),
  m({
    inci: 'Pentylene Glycol',
    roles: ['humectant', 'preservative_booster'],
    phase: 'water',
    typical: [1, 5],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Multifunctional: humectant plus antimicrobial support at 3–5%.',
  }),
  m({
    inci: '1,2-Hexanediol',
    roles: ['preservative_booster', 'humectant'],
    phase: 'water',
    typical: [0.5, 2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
  }),
  m({
    inci: 'Sodium Hyaluronate',
    aliases: ['Hyaluronic acid', 'HA'],
    roles: ['humectant', 'active'],
    phase: 'water',
    typical: [0.05, 1],
    max: 2,
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sprinkle into water and let it hydrate, or pre-disperse in glycerin. Above 1% the base gets very thick.',
  }),
  m({
    inci: 'Betaine',
    roles: ['humectant'],
    phase: 'water',
    typical: [1, 5],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sugar-beet derived. Soft, non-sticky humectant.',
  }),
  m({
    inci: 'Sodium PCA',
    roles: ['humectant'],
    phase: 'water',
    typical: [0.5, 2.5],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Sodium Lactate',
    roles: ['humectant', 'ph_adjuster'],
    phase: 'water',
    typical: [0.5, 3],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Panthenol',
    aliases: ['D-Panthenol', 'Pro-vitamin B5'],
    roles: ['active', 'humectant'],
    phase: 'cool_down',
    typical: [0.5, 5],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Add below 40 °C. Soothing; pairs well with allantoin and niacinamide.',
  }),
  m({
    inci: 'Allantoin',
    roles: ['active'],
    phase: 'water',
    typical: [0.1, 0.5],
    max: 0.5,
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Dissolve in the heated water phase. Above 0.5% it recrystallises.',
  }),
  m({
    inci: 'Niacinamide',
    aliases: ['Vitamin B3'],
    roles: ['active'],
    phase: 'water',
    typical: [2, 5],
    max: 10,
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Keep final pH 5–7. Do not combine with low-pH ascorbic acid.',
  }),
  m({
    inci: 'Urea',
    roles: ['active', 'humectant'],
    phase: 'cool_down',
    typical: [2, 10],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Buffer pH 6–6.5 (sodium lactate / lactic acid) or it breaks down to ammonia.',
  }),
  m({
    inci: 'Aloe Barbadensis Leaf Juice',
    aliases: ['Aloe vera juice', 'Aloe juice'],
    roles: ['active', 'water'],
    phase: 'water',
    typical: [1, 20],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Can replace part of the water. Preserved grades only.',
  }),
  m({
    inci: 'Rosa Damascena Flower Water',
    aliases: ['Rose hydrosol', 'Rose water'],
    roles: ['water', 'active'],
    phase: 'water',
    typical: [5, 40],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Hydrosol. Counts as water for preservation.',
  }),
  m({
    inci: 'Disodium EDTA',
    aliases: ['EDTA'],
    roles: ['chelator'],
    phase: 'water',
    typical: [0.05, 0.2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Dissolve first in the water phase. Protects the preservative and colour.',
  }),
  m({
    inci: 'Tetrasodium Glutamate Diacetate',
    aliases: ['GLDA', 'Dissolvine GL'],
    roles: ['chelator'],
    phase: 'water',
    typical: [0.05, 0.3],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Biodegradable, natural-friendly alternative to EDTA.',
  }),
  m({
    inci: 'Sodium Phytate',
    aliases: ['Phytic acid sodium salt'],
    roles: ['chelator'],
    phase: 'water',
    typical: [0.05, 0.2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'COSMOS-friendly chelator from rice bran.',
  }),
  m({
    inci: 'Xanthan Gum',
    roles: ['thickener'],
    phase: 'water',
    typical: [0.1, 0.5],
    max: 1,
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Disperse in glycerin before adding to water to avoid lumps. Stabilises emulsions.',
  }),
  m({
    inci: 'Sclerotium Gum',
    aliases: ['Amigel'],
    roles: ['thickener'],
    phase: 'water',
    typical: [0.2, 1],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Silkier than xanthan, tolerates electrolytes.',
  }),
  m({
    inci: 'Hydroxyethylcellulose',
    aliases: ['HEC', 'Natrosol'],
    roles: ['thickener'],
    phase: 'water',
    typical: [0.3, 1],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Clear gels. Disperse cold, then heat to hydrate.',
  }),
  m({
    inci: 'Carbomer',
    aliases: ['Carbopol'],
    roles: ['thickener'],
    phase: 'water',
    typical: [0.1, 0.5],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Neutralise to pH ~6 with sodium hydroxide or arginine to thicken. Sensitive to salt.',
  }),
  m({
    inci: 'Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
    aliases: ['Carbopol Ultrez 21', 'Pemulen'],
    roles: ['thickener', 'emulsifier'],
    phase: 'water',
    typical: [0.1, 0.4],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Neutralise to activate. Stabilises light emulsions.',
  }),
  m({
    inci: 'Citric Acid',
    roles: ['ph_adjuster'],
    phase: 'cool_down',
    typical: [0.05, 0.5],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Use as a 10–50% solution to bring pH down. Add drop by drop, measure.',
  }),
  m({
    inci: 'Lactic Acid',
    roles: ['ph_adjuster', 'active'],
    phase: 'cool_down',
    typical: [0.1, 2],
    max: 5,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'pH adjuster at low levels; exfoliating AHA above ~2%.',
  }),
  m({
    inci: 'Sodium Hydroxide',
    aliases: ['NaOH', 'Lye'],
    roles: ['ph_adjuster'],
    phase: 'cool_down',
    typical: [0.01, 0.3],
    max: 0.5,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Use as a 10% solution to bring pH up or neutralise carbomer.',
  }),
  m({
    inci: 'Triethanolamine',
    aliases: ['TEA'],
    roles: ['ph_adjuster'],
    phase: 'cool_down',
    typical: [0.1, 1],
    max: 2.5,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'EU limit 2.5% in leave-on. Prefer sodium hydroxide or arginine for natural claims.',
  }),
  m({
    inci: 'Arginine',
    aliases: ['L-Arginine'],
    roles: ['ph_adjuster'],
    phase: 'cool_down',
    typical: [0.1, 1],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Amino acid base. Natural-friendly way to raise pH or neutralise carbomer.',
  }),

  // ------------------------------------------------------------------ oil phase
  m({
    inci: 'Squalane',
    aliases: ['Olive squalane', 'Sugarcane squalane'],
    cas: '111-01-3',
    roles: ['emollient', 'carrier'],
    phase: 'oil',
    typical: [2, 80],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Very stable, light, non-comedogenic. Plant-derived grades only for vegan.',
  }),
  m({
    inci: 'Caprylic/Capric Triglyceride',
    aliases: ['MCT oil', 'Fractionated coconut oil', 'Neutral oil'],
    cas: '73398-61-5',
    roles: ['emollient', 'carrier'],
    phase: 'oil',
    typical: [2, 90],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Odourless, very stable. Standard carrier for oil perfumes.',
  }),
  m({
    inci: 'Simmondsia Chinensis Seed Oil',
    aliases: ['Jojoba oil', 'Simmondsia Chinensis (Jojoba) Seed Oil'],
    roles: ['emollient', 'carrier'],
    phase: 'oil',
    typical: [2, 90],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Liquid wax, close to skin sebum, very shelf-stable.',
  }),
  m({
    inci: 'Prunus Amygdalus Dulcis Oil',
    aliases: ['Sweet almond oil', 'Prunus Amygdalus Dulcis (Sweet Almond) Oil'],
    roles: ['emollient', 'carrier'],
    phase: 'oil',
    typical: [2, 60],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Nut allergen — flag on the label.',
  }),
  m({
    inci: 'Helianthus Annuus Seed Oil',
    aliases: ['Sunflower oil', 'Helianthus Annuus (Sunflower) Seed Oil'],
    roles: ['emollient', 'carrier'],
    phase: 'oil',
    typical: [2, 60],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'High-oleic grade keeps better.',
  }),
  m({
    inci: 'Vitis Vinifera Seed Oil',
    aliases: ['Grapeseed oil', 'Vitis Vinifera (Grape) Seed Oil'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 40],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Light, dry feel. Oxidises; keep an antioxidant in.',
  }),
  m({
    inci: 'Rosa Canina Seed Oil',
    aliases: ['Rosehip oil', 'Rosa Canina Fruit Oil'],
    roles: ['emollient', 'active'],
    phase: 'oil',
    typical: [1, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Fragile. Keep under 20% and always with tocopherol.',
  }),
  m({
    inci: 'Argania Spinosa Kernel Oil',
    aliases: ['Argan oil'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [1, 30],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Camellia Japonica Seed Oil',
    aliases: ['Camellia oil', 'Tsubaki oil'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 50],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Oenothera Biennis Oil',
    aliases: ['Evening primrose oil', 'Oenothera Biennis (Evening Primrose) Oil'],
    roles: ['emollient', 'active'],
    phase: 'oil',
    typical: [1, 10],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'GLA-rich, oxidises fast. Keep low, protect with antioxidant.',
  }),
  m({
    inci: 'Cannabis Sativa Seed Oil',
    aliases: ['Hemp seed oil'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [1, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Fragile, green. Needs antioxidant.',
  }),
  m({
    inci: 'Persea Gratissima Oil',
    aliases: ['Avocado oil', 'Persea Gratissima (Avocado) Oil'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Rich, good for dry skin and body products.',
  }),
  m({
    inci: 'Coco-Caprylate/Caprate',
    aliases: ['Cetiol C5'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Natural-derived dry ester. Fast-absorbing, cuts greasiness.',
  }),
  m({
    inci: 'Isoamyl Laurate',
    aliases: ['Dermofeel Sensolv'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 15],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Natural silicone alternative, very light.',
  }),
  m({
    inci: 'Dicaprylyl Carbonate',
    aliases: ['Cetiol CC'],
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 15],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Dry, fast-spreading ester.',
  }),
  m({
    inci: 'C12-15 Alkyl Benzoate',
    roles: ['emollient'],
    phase: 'oil',
    typical: [2, 15],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
  }),
  m({
    inci: 'Isopropyl Myristate',
    aliases: ['IPM'],
    roles: ['emollient', 'carrier', 'solvent'],
    phase: 'oil',
    typical: [1, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Thin, dry ester. Common diluent for oil perfumes and aroma materials.',
  }),
  m({
    inci: 'Dimethicone',
    roles: ['emollient'],
    phase: 'oil',
    typical: [1, 10],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Slip and protection. Not for natural claims.',
  }),
  m({
    inci: 'Butyrospermum Parkii Butter',
    aliases: ['Shea Butter', 'Butyrospermum Parkii (Shea) Butter'],
    roles: ['butter', 'emollient'],
    phase: 'oil',
    typical: [2, 30],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Melt fully (>75 °C) and cool fast to avoid grainy texture.',
  }),
  m({
    inci: 'Theobroma Cacao Seed Butter',
    aliases: ['Cocoa Butter', 'Theobroma Cacao (Cocoa) Seed Butter'],
    roles: ['butter'],
    phase: 'oil',
    typical: [2, 25],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Hard butter. Adds structure to balms and solid perfumes.',
  }),
  m({
    inci: 'Mangifera Indica Seed Butter',
    aliases: ['Mango Butter', 'Mangifera Indica (Mango) Seed Butter'],
    roles: ['butter'],
    phase: 'oil',
    typical: [2, 25],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Less greasy than shea. Unscented.',
  }),
  m({
    inci: 'Cetearyl Alcohol',
    roles: ['co_emulsifier', 'thickener'],
    phase: 'oil',
    typical: [1, 6],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Fatty alcohol. Gives body and stabilises the emulsion.',
  }),
  m({
    inci: 'Cetyl Alcohol',
    roles: ['co_emulsifier', 'thickener'],
    phase: 'oil',
    typical: [1, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Lighter than cetearyl alcohol. Powdery finish.',
  }),
  m({
    inci: 'Stearic Acid',
    roles: ['co_emulsifier', 'thickener'],
    phase: 'oil',
    typical: [1, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Plant-derived grades exist. Firm, classic cream body.',
  }),
  m({
    inci: 'Cetyl Palmitate',
    roles: ['co_emulsifier', 'wax'],
    phase: 'oil',
    typical: [1, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Glyceryl Stearate',
    aliases: ['GMS'],
    roles: ['co_emulsifier', 'emulsifier'],
    phase: 'oil',
    typical: [1, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Low-HLB helper. Pair with a primary O/W emulsifier.',
  }),
  m({
    inci: 'Glyceryl Stearate Citrate',
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [2, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Natural O/W emulsifier. Add 1–3% cetearyl alcohol for stability.',
  }),
  m({
    inci: 'Glyceryl Stearate SE',
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [2, 6],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Self-emulsifying grade; works alone in simple lotions.',
  }),
  m({
    inci: 'Cetearyl Olivate',
    aliases: ['Olivem 1000 (part)'],
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [2, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sold with Sorbitan Olivate as Olivem 1000. Use both rows at a 3–8% combined total.',
  }),
  m({
    inci: 'Sorbitan Olivate',
    aliases: ['Olivem 1000 (part)'],
    roles: ['co_emulsifier', 'emulsifier'],
    phase: 'oil',
    typical: [1, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Second half of Olivem 1000. Always with Cetearyl Olivate.',
  }),
  m({
    inci: 'Polyglyceryl-3 Methylglucose Distearate',
    aliases: ['Tego Care 450'],
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [2, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Gentle natural O/W emulsifier, light creams and lotions.',
  }),
  m({
    inci: 'Cetearyl Glucoside',
    aliases: ['Montanov 68 (part)'],
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [1, 4],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sold blended with Cetearyl Alcohol (Montanov 68). Liquid-crystal texture.',
  }),
  m({
    inci: 'Sodium Stearoyl Glutamate',
    aliases: ['Eumulgin SG'],
    roles: ['co_emulsifier'],
    phase: 'water',
    typical: [0.3, 2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Anionic helper that boosts natural emulsifiers. Goes in the water phase.',
  }),
  m({
    inci: 'Potassium Cetyl Phosphate',
    aliases: ['Amphisol K'],
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [0.5, 3],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Anionic, very stable emulsions. Pair with glyceryl stearate.',
  }),
  m({
    inci: 'Ceteareth-20',
    roles: ['emulsifier'],
    phase: 'oil',
    typical: [1, 4],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Classic ethoxylated emulsifier. Not for natural claims.',
  }),
  m({
    inci: 'Polysorbate 20',
    aliases: ['Tween 20'],
    roles: ['solubilizer'],
    phase: 'water',
    typical: [0.5, 5],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Solubilises fragrance or essential oils in water. Use 3–5× the oil amount.',
  }),
  m({
    inci: 'Polysorbate 80',
    aliases: ['Tween 80'],
    roles: ['solubilizer'],
    phase: 'water',
    typical: [0.5, 5],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
  }),
  m({
    inci: 'PEG-40 Hydrogenated Castor Oil',
    aliases: ['Cremophor RH40'],
    roles: ['solubilizer'],
    phase: 'water',
    typical: [0.5, 3],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
  }),
  m({
    inci: 'Caprylyl/Capryl Glucoside',
    roles: ['solubilizer'],
    phase: 'water',
    typical: [0.5, 5],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Natural solubiliser for small oil loads in toners and mists.',
  }),
  m({
    inci: 'Lecithin',
    roles: ['emulsifier', 'active'],
    phase: 'oil',
    typical: [0.5, 3],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sunflower or soy grades. Helper emulsifier and skin-barrier lipid.',
  }),
  m({
    inci: 'Cera Alba',
    aliases: ['Beeswax', 'Cera Alba (Beeswax)'],
    roles: ['wax'],
    phase: 'oil',
    typical: [2, 25],
    solubility: 'oil',
    animalDerived: 'yes',
    originType: 'natural',
    notes: 'Animal-derived. Blocks vegan products. Melt at 62–65 °C.',
  }),
  m({
    inci: 'Euphorbia Cerifera Cera',
    aliases: ['Candelilla wax', 'Euphorbia Cerifera (Candelilla) Wax'],
    roles: ['wax'],
    phase: 'oil',
    typical: [2, 20],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Vegan beeswax stand-in. Harder — use about 20% less than beeswax.',
  }),
  m({
    inci: 'Copernicia Cerifera Cera',
    aliases: ['Carnauba wax', 'Copernicia Cerifera (Carnauba) Wax'],
    roles: ['wax'],
    phase: 'oil',
    typical: [1, 10],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Very hard, high melt (~83 °C). Small amounts for firmness and gloss.',
  }),
  m({
    inci: 'Helianthus Annuus Seed Cera',
    aliases: ['Sunflower wax', 'Helianthus Annuus (Sunflower) Seed Wax'],
    roles: ['wax'],
    phase: 'oil',
    typical: [1, 10],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Odourless vegan wax. Good for solid perfumes.',
  }),
  m({
    inci: 'Tocopherol',
    aliases: ['Vitamin E', 'Mixed tocopherols'],
    cas: '59-02-9',
    roles: ['antioxidant'],
    phase: 'cool_down',
    typical: [0.05, 1],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Protects oils from going rancid. 0.1–0.5% is the working band.',
  }),
  m({
    inci: 'Tocopheryl Acetate',
    aliases: ['Vitamin E acetate'],
    roles: ['active', 'antioxidant'],
    phase: 'cool_down',
    typical: [0.5, 2],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Skin-conditioning ester. Does not protect the oil phase — use Tocopherol for that.',
  }),
  m({
    inci: 'Rosmarinus Officinalis Leaf Extract',
    aliases: ['Rosemary CO2 extract', 'Rosemary antioxidant', 'ROE'],
    roles: ['antioxidant'],
    phase: 'cool_down',
    typical: [0.02, 0.2],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Strong natural antioxidant. Slight herbal smell above 0.1%.',
  }),
  m({
    inci: 'Ascorbyl Palmitate',
    roles: ['antioxidant'],
    phase: 'oil',
    typical: [0.05, 0.3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Works with tocopherol in oils.',
  }),

  // -------------------------------------------------------------- actives (oil)
  m({
    inci: 'Ceramide NP',
    aliases: ['Ceramide 3'],
    roles: ['active'],
    phase: 'oil',
    typical: [0.05, 0.5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Dissolve in the hot oil phase. Pair with cholesterol and fatty acids for barrier work.',
  }),
  m({
    inci: 'Bisabolol',
    aliases: ['Alpha-bisabolol'],
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.1, 1],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Soothing. Candeia-derived or synthetic grades.',
  }),
  m({
    inci: 'Bakuchiol',
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.5, 1],
    max: 2,
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Retinol-like plant active. Protect from light.',
  }),
  m({
    inci: 'Retinyl Palmitate',
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.1, 1],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Gentle vitamin A ester. Light-sensitive; opaque packaging.',
  }),
  m({
    inci: 'Tetrahexyldecyl Ascorbate',
    aliases: ['THD ascorbate', 'Oil-soluble vitamin C'],
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.5, 3],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Stable oil-soluble vitamin C for face oils.',
  }),
  m({
    inci: '3-O-Ethyl Ascorbic Acid',
    roles: ['active'],
    phase: 'cool_down',
    typical: [1, 3],
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Water-soluble stable vitamin C. pH 4–5.5.',
  }),
  m({
    inci: 'Zinc PCA',
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.1, 1],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Sebum control. Can destabilise carbomer.',
  }),
  m({
    inci: 'Salicylic Acid',
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.5, 2],
    max: 2,
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'EU max 2% in leave-on. Not for children under 3. pH 3–4 to work.',
  }),
  m({
    inci: 'Caffeine',
    roles: ['active'],
    phase: 'water',
    typical: [0.5, 2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Dissolves in warm water phase. Eye-area products.',
  }),
  m({
    inci: 'Centella Asiatica Extract',
    aliases: ['Cica extract', 'Gotu kola extract'],
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.5, 3],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Camellia Sinensis Leaf Extract',
    aliases: ['Green tea extract'],
    roles: ['active', 'antioxidant'],
    phase: 'cool_down',
    typical: [0.5, 2],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
  }),
  m({
    inci: 'Calendula Officinalis Flower Extract',
    aliases: ['Calendula extract'],
    roles: ['active'],
    phase: 'cool_down',
    typical: [0.5, 3],
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Oil-infused or glycerin-based grades; match the phase to the grade.',
  }),
  m({
    inci: 'Avena Sativa Kernel Flour',
    aliases: ['Colloidal oatmeal', 'Avena Sativa (Oat) Kernel Flour'],
    roles: ['active'],
    phase: 'water',
    typical: [0.5, 2],
    solubility: 'water',
    animalDerived: 'no',
    originType: 'natural',
  }),

  // -------------------------------------------------------------- preservatives
  m({
    inci: 'Phenoxyethanol',
    cas: '122-99-6',
    roles: ['preservative'],
    phase: 'cool_down',
    typical: [0.5, 1],
    max: 1,
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'EU max 1%. Broad spectrum; pair with ethylhexylglycerin.',
  }),
  m({
    inci: 'Ethylhexylglycerin',
    roles: ['preservative_booster'],
    phase: 'cool_down',
    typical: [0.2, 1],
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Booster, not a preservative on its own. Sold with phenoxyethanol as Euxyl PE 9010 (1% total).',
  }),
  m({
    inci: 'Benzyl Alcohol',
    roles: ['preservative', 'solvent'],
    phase: 'cool_down',
    typical: [0.5, 1],
    max: 1,
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'EU max 1% as preservative. Fragrance allergen — must appear on label. Nature-identical grades exist.',
  }),
  m({
    inci: 'Dehydroacetic Acid',
    roles: ['preservative'],
    phase: 'cool_down',
    typical: [0.1, 0.6],
    max: 0.6,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Sold with benzyl alcohol as Geogard 221 (0.6–1% total). Needs pH below 6.',
  }),
  m({
    inci: 'Sodium Benzoate',
    roles: ['preservative'],
    phase: 'cool_down',
    typical: [0.2, 0.5],
    max: 0.5,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'EU max 0.5% leave-on. Only works below pH 5.5. Pair with potassium sorbate.',
  }),
  m({
    inci: 'Potassium Sorbate',
    roles: ['preservative'],
    phase: 'cool_down',
    typical: [0.1, 0.3],
    max: 0.6,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Anti-mould. Needs pH below 5.5. Pair with sodium benzoate.',
  }),
  m({
    inci: 'Gluconolactone',
    roles: ['preservative_booster', 'active'],
    phase: 'cool_down',
    typical: [0.5, 2],
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Sold with sodium benzoate as Geogard Ultra (0.75–2%). Mild PHA.',
  }),
  m({
    inci: 'Caprylhydroxamic Acid',
    roles: ['preservative_booster', 'chelator'],
    phase: 'cool_down',
    typical: [0.1, 0.2],
    solubility: 'both',
    coolDown: true,
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Anti-fungal chelator. Sold as Spectrastat blends with glycols.',
  }),
  m({
    inci: 'Chlorphenesin',
    roles: ['preservative'],
    phase: 'cool_down',
    typical: [0.1, 0.3],
    max: 0.3,
    solubility: 'water',
    coolDown: true,
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'EU max 0.3%. Often paired with phenoxyethanol.',
  }),

  // ------------------------------------------------------------ fragrance (skin)
  m({
    inci: 'Parfum',
    aliases: ['Fragrance', 'Fragrance compound', 'Parfum compound', 'Perfume oil'],
    roles: ['fragrance_compound'],
    phase: 'cool_down',
    typical: [0.1, 1],
    solubility: 'oil',
    coolDown: true,
    animalDerived: 'unknown',
    originType: 'synthetic',
    notes: 'Finished fragrance compound for skincare. EU label word is "Parfum". Skincare 0.2–1%. For a perfume product, list the aroma materials individually instead.',
  }),

  // -------------------------------------------------- perfume solvents / carriers
  m({
    inci: 'Alcohol Denat.',
    aliases: ['Perfumers alcohol', 'Denatured ethanol', 'SD Alcohol 40-B'],
    roles: ['solvent'],
    phase: 'solvent',
    typical: [60, 90],
    solubility: 'alcohol',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Balance of an alcohol perfume. 96% cosmetic grade. Macerate 2–6 weeks, chill, filter.',
  }),
  m({
    inci: 'Alcohol',
    aliases: ['Ethanol', 'Undenatured alcohol'],
    roles: ['solvent'],
    phase: 'solvent',
    typical: [60, 90],
    solubility: 'alcohol',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Undenatured ethanol. Excise rules apply in most countries.',
  }),
  m({
    inci: 'Dipropylene Glycol',
    aliases: ['DPG'],
    roles: ['solvent', 'fixative'],
    phase: 'concentrate',
    typical: [0.5, 10],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Odourless diluent for aroma materials. Slows evaporation slightly.',
  }),
  m({
    inci: 'Benzyl Benzoate',
    roles: ['solvent', 'fixative', 'aroma_material'],
    phase: 'concentrate',
    typical: [0.5, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Faint balsamic. Diluent and fixative. EU allergen — label above threshold.',
  }),
  m({
    inci: 'Triethyl Citrate',
    roles: ['solvent', 'fixative'],
    phase: 'concentrate',
    typical: [0.5, 5],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Odourless natural-derived fixative and diluent.',
  }),

  // ------------------------------------------------- aroma materials (synthetic)
  m({
    inci: 'Linalool',
    cas: '78-70-6',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Fresh floral top. EU allergen. Add antioxidant — oxidised linalool sensitises.',
  }),
  m({
    inci: 'Limonene',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Citrus top. EU allergen. Oxidises — keep an antioxidant in.',
  }),
  m({
    inci: 'Citral',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.3],
    max: 0.6,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Lemon. IFRA-restricted; EU allergen.',
  }),
  m({
    inci: 'Geraniol',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    max: 3,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Rosy. EU allergen.',
  }),
  m({
    inci: 'Citronellol',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Fresh rosy. EU allergen.',
  }),
  m({
    inci: 'Eugenol',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.3],
    max: 0.5,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Clove. IFRA-restricted; EU allergen.',
  }),
  m({
    inci: 'Isoeugenol',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.001, 0.02],
    max: 0.02,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Carnation. IFRA cat 4 limit ~0.02%. Trace use only.',
  }),
  m({
    inci: 'Cinnamal',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.001, 0.05],
    max: 0.05,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Cinnamon. IFRA cat 4 limit ~0.05%. Trace use only.',
  }),
  m({
    inci: 'Farnesol',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Soft floral-green. EU allergen.',
  }),
  m({
    inci: 'Coumarin',
    cas: '91-64-5',
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.05, 0.5],
    max: 0.6,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Hay, tonka. IFRA-restricted; EU allergen.',
  }),
  m({
    inci: 'Benzyl Salicylate',
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Soft floral blender and fixative. EU allergen.',
  }),
  m({
    inci: 'Hexyl Cinnamal',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Jasmine-like. EU allergen.',
  }),
  m({
    inci: 'Alpha-Isomethyl Ionone',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    allergen: true,
    notes: 'Violet, woody-floral. EU allergen.',
  }),
  m({
    inci: 'Tetramethyl Acetyloctahydronaphthalenes',
    aliases: ['Iso E Super'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.5, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Velvety woody-amber. Backbone of many modern perfumes.',
  }),
  m({
    inci: 'Methyl Dihydrojasmonate',
    aliases: ['Hedione'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.5, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Airy jasmine, lifts everything. Can run high.',
  }),
  m({
    inci: 'Hexamethylindanopyran',
    aliases: ['Galaxolide'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.3, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Clean musk fixative. Sold at 50% in a solvent.',
  }),
  m({
    inci: 'Ethylene Brassylate',
    aliases: ['Musk T'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.5, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Soft powdery musk. Cheap fixative, good in oil perfumes.',
  }),
  m({
    inci: 'Dodecahydro-3a,6,6,9a-Tetramethylnaphtho(2,1-b)furan',
    aliases: ['Ambroxan', 'Ambroxide', 'Ambrofix'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Dry ambergris. Crystals — dissolve in alcohol or DPG first.',
  }),
  m({
    inci: 'Vanillin',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Sweet vanilla. Discolours to brown over time.',
  }),
  m({
    inci: 'Phenethyl Alcohol',
    aliases: ['Phenylethyl alcohol', 'PEA'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'both',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Rose petal. Also mild preservative helper.',
  }),
  m({
    inci: 'Benzyl Acetate',
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Jasmine, fruity. Volatile top.',
  }),

  // --------------------------------------------------- aroma materials (natural)
  m({
    inci: 'Citrus Aurantium Bergamia Fruit Oil',
    aliases: ['Bergamot oil', 'Citrus Aurantium Bergamia (Bergamot) Fruit Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    max: 2,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Use FCF (bergapten-free) grade for leave-on. Contains linalool, limonene.',
  }),
  m({
    inci: 'Citrus Limon Peel Oil',
    aliases: ['Lemon oil', 'Citrus Limon (Lemon) Peel Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    max: 2,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Phototoxic cold-pressed grades; keep IFRA leave-on limit. Contains limonene, citral.',
  }),
  m({
    inci: 'Citrus Aurantium Dulcis Peel Oil',
    aliases: ['Sweet orange oil', 'Citrus Aurantium Dulcis (Orange) Peel Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Not phototoxic. Mostly limonene — label it.',
  }),
  m({
    inci: 'Citrus Paradisi Peel Oil',
    aliases: ['Grapefruit oil', 'Citrus Paradisi (Grapefruit) Peel Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Limonene-rich. Fades fast — pair with a fixative.',
  }),
  m({
    inci: 'Citrus Aurantium Amara Flower Oil',
    aliases: ['Neroli oil', 'Citrus Aurantium Amara (Bitter Orange) Flower Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Green orange blossom. Contains linalool, limonene.',
  }),
  m({
    inci: 'Citrus Aurantium Amara Leaf/Twig Oil',
    aliases: ['Petitgrain oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Woody-green neroli stand-in. Contains linalool.',
  }),
  m({
    inci: 'Lavandula Angustifolia Oil',
    aliases: ['Lavender oil', 'Lavandula Angustifolia (Lavender) Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Contains linalool and linalyl acetate — allergen labelling.',
  }),
  m({
    inci: 'Rosa Damascena Flower Oil',
    aliases: ['Rose otto', 'Rose oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Very expensive. Contains citronellol, geraniol, eugenol. Sold at 10% dilution often.',
  }),
  m({
    inci: 'Pelargonium Graveolens Flower Oil',
    aliases: ['Geranium oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Rosy-green, affordable rose helper. Contains citronellol, geraniol, linalool.',
  }),
  m({
    inci: 'Jasminum Grandiflorum Flower Extract',
    aliases: ['Jasmine absolute'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.5],
    max: 0.7,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'IFRA-restricted. Contains benzyl acetate, benzyl benzoate.',
  }),
  m({
    inci: 'Cananga Odorata Flower Oil',
    aliases: ['Ylang ylang oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Creamy floral. IFRA-restricted. Contains benzyl benzoate, isoeugenol.',
  }),
  m({
    inci: 'Cedrus Atlantica Bark Oil',
    aliases: ['Atlas cedarwood oil'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 3],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Dry woody base. Cheap, long-lasting.',
  }),
  m({
    inci: 'Santalum Album Oil',
    aliases: ['Sandalwood oil'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Creamy wood fixative. Very expensive; Australian Santalum Spicatum is a cheaper swap.',
  }),
  m({
    inci: 'Vetiveria Zizanoides Root Oil',
    aliases: ['Vetiver oil'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Earthy-smoky base. Thick — warm before weighing.',
  }),
  m({
    inci: 'Pogostemon Cablin Oil',
    aliases: ['Patchouli oil', 'Pogostemon Cablin (Patchouli) Oil'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Earthy base fixative. Improves with age.',
  }),
  m({
    inci: 'Boswellia Carterii Oil',
    aliases: ['Frankincense oil', 'Olibanum oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.1, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Resinous-citrus. Contains limonene.',
  }),
  m({
    inci: 'Cistus Ladaniferus Resin',
    aliases: ['Labdanum absolute', 'Labdanum'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Amber base. Sticky — dilute in alcohol or DPG first.',
  }),
  m({
    inci: 'Vanilla Planifolia Fruit Extract',
    aliases: ['Vanilla absolute', 'Vanilla Absolute'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Warm, expensive. Vanillin is the cheap stand-in.',
  }),
  m({
    inci: 'Styrax Benzoin Resin Extract',
    aliases: ['Benzoin resinoid', 'Benzoin'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Sweet balsamic fixative. Contains benzyl benzoate, benzyl alcohol.',
  }),
  m({
    inci: 'Dipteryx Odorata Seed Extract',
    aliases: ['Tonka bean absolute', 'Tonka'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.05, 0.5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Coumarin-rich — count it toward the coumarin limit.',
  }),
  m({
    inci: 'Evernia Prunastri Extract',
    aliases: ['Oakmoss absolute', 'Oakmoss'],
    roles: ['aroma_material', 'fixative'],
    phase: 'concentrate',
    typical: [0.01, 0.1],
    max: 0.1,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Atranol-free grade only. EU-restricted allergen. Trace use.',
  }),
  m({
    inci: 'Iris Pallida Root Extract',
    aliases: ['Orris butter', 'Iris absolute'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.01, 0.2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    notes: 'Powdery violet. Extremely expensive; alpha-isomethyl ionone stands in.',
  }),
  m({
    inci: 'Piper Nigrum Seed Oil',
    aliases: ['Black pepper oil', 'Piper Nigrum (Pepper) Seed Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Spicy top. Contains limonene.',
  }),
  m({
    inci: 'Elettaria Cardamomum Seed Oil',
    aliases: ['Cardamom oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 0.5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Fresh spice. Contains linalool, limonene.',
  }),
  m({
    inci: 'Salvia Sclarea Oil',
    aliases: ['Clary sage oil', 'Salvia Sclarea (Clary) Oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.05, 1],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Herbal-ambery. Contains linalool, linalyl acetate.',
  }),
  m({
    inci: 'Cinnamomum Zeylanicum Bark Oil',
    aliases: ['Cinnamon bark oil'],
    roles: ['aroma_material'],
    phase: 'concentrate',
    typical: [0.001, 0.05],
    max: 0.05,
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'natural',
    allergen: true,
    notes: 'Cinnamal-rich. IFRA limit applies to the cinnamal content. Trace use only.',
  }),

  // ------------------------------------------------------------------ colourants
  m({
    inci: 'CI 77891',
    aliases: ['Titanium Dioxide'],
    roles: ['colorant'],
    phase: 'oil',
    typical: [0.1, 5],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'White opacifier for balms. Listed last on the EU label.',
  }),
  m({
    inci: 'CI 77491',
    aliases: ['Iron Oxide Red'],
    roles: ['colorant'],
    phase: 'oil',
    typical: [0.05, 2],
    solubility: 'oil',
    animalDerived: 'no',
    originType: 'synthetic',
    notes: 'Tint for balms and solid perfumes. Listed last on the EU label.',
  }),
]

const MATERIAL_INDEX: Map<string, Material> = (() => {
  const index = new Map<string, Material>()
  for (const material of MATERIALS) {
    index.set(normalizeInci(material.inci), material)
    for (const alias of material.aliases ?? []) {
      const key = normalizeInci(alias)
      if (!index.has(key)) index.set(key, material)
    }
  }
  return index
})()

/** Match an INCI or a known trade/common name to a library material. */
export function findMaterial(inci: string): Material | undefined {
  const key = normalizeInci(inci).replace(/\s+/g, ' ')
  return MATERIAL_INDEX.get(key)
}

/** Every name a material may be filed under on the shelf: its INCI plus known aliases. */
export function materialKeys(material: Material): string[] {
  return [material.inci, ...(material.aliases ?? [])].map((name) => normalizeInci(name))
}

/**
 * Look a row up on the shelf. The shelf may say "Shea Butter" while the row says
 * "Butyrospermum Parkii Butter", so try the INCI, then every alias the library knows.
 */
export function findOnShelf<T extends { inci: string }>(inci: string, shelf: T[], material = findMaterial(inci)): T | undefined {
  const keys = new Set([normalizeInci(inci), ...(material ? materialKeys(material) : [])])
  return shelf.find((item) => keys.has(normalizeInci(item.inci)))
}

export function materialsForRole(role: MaterialRole): Material[] {
  return MATERIALS.filter((material) => material.roles.includes(role))
}

export function searchMaterials(query: string, options?: { role?: MaterialRole; limit?: number }) {
  const q = normalizeInci(query)
  const limit = options?.limit ?? 20
  const matches = MATERIALS.filter((material) => {
    if (options?.role && !material.roles.includes(options.role)) return false
    if (!q) return true
    return (
      normalizeInci(material.inci).includes(q) ||
      (material.aliases ?? []).some((alias) => normalizeInci(alias).includes(q)) ||
      material.roles.some((role) => role.includes(q) || MATERIAL_ROLE_LABELS[role].toLowerCase().includes(q)) ||
      (material.notes ?? '').toLowerCase().includes(q)
    )
  })
  return matches.slice(0, limit)
}
